# --- !Ups

create table "exercisesets" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "date" date not null
);

# --- !Downs

drop table "exercisesets" if exists;